#!/usr/bin/php
<?php
/* Author : Romain "Artefact2" Dalmaso <artefact2@gmail.com>
* This program is free software. It comes without any warranty, to
* the extent permitted by applicable law. You can redistribute it
* and/or modify it under the terms of the Do What The Fuck You Want
* To Public License, Version 2, as published by Sam Hocevar. See
* http://sam.zoy.org/wtfpl/COPYING for more details. */

require __DIR__.'/lib.php';

$jsonstring = stream_get_contents(STDIN);

/* $errors is passed by reference */
$returncode = \CommonLoadoutFormat\validate_clf($jsonstring, $errors);

foreach($errors as $err) {
	fprintf(STDERR, $err.".\n");
}

die($returncode);
