#!/usr/bin/env php
<?php
/* Author : Romain "Artefact2" Dalmaso <artefact2@gmail.com>
 * This program is free software. It comes without any warranty, to
 * the extent permitted by applicable law. You can redistribute it
 * and/or modify it under the terms of the Do What The Fuck You Want
 * To Public License, Version 2, as published by Sam Hocevar. See
 * http://sam.zoy.org/wtfpl/COPYING for more details. */

/* Create a JSON map (moduleid => [chargeid]) of all the published
 * fittable charges, and the modules they can be fitted to.
 */

require __DIR__.'/sqlite_script_common.php';

/** SDEs use "dgmtypeattributes" and "dgmattributetypes", whereas
 * dumps created by the Eos dumper uses "dgmtypeattribs" and
 * "dgmattribs" instead. This function returns the correct table
 * names. */
function getdgmattribs(SQLite3 $db) {
	$q = $db->query("SELECT name FROM sqlite_master WHERE type='table' AND name IN ('dgmattribs', 'dgmattributetypes')");
	list($tablename) = $q->fetchArray(SQLITE3_NUM);

	if($tablename == 'dgmattribs') {
		/* Eos dump */
		return array('dgmattribs', 'dgmtypeattribs', '%.value');
	} else {
		/* SDE */
		return array('dgmattributetypes', 'dgmtypeattributes', 'COALESCE(%.valuefloat, %.valueint)');
	}
}

function process(SQLite3 $db, array &$charges) {
	list($dgmattribs, $dgmtypeattribs, $value) = getdgmattribs($db);
	$modattribsvalue = str_replace('%', 'modattribs', $value);
	$chargesizevalue = str_replace('%', 'chargesize', $value);
	$modchargesizevalue = str_replace('%', 'modchargesize', $value);

	$req = $db->query("
SELECT modattribs.typeid AS moduleid, invtypes.typeid AS chargeid
FROM $dgmtypeattribs AS modattribs
LEFT JOIN $dgmtypeattribs modchargesize ON modchargesize.attributeid = 128
                                           AND modchargesize.typeid = modattribs.typeid 
JOIN invtypes ON $modattribsvalue = invtypes.groupid
LEFT JOIN $dgmtypeattribs AS chargesize ON chargesize.attributeid = 128
                                           AND chargesize.typeid = invtypes.typeid
WHERE modattribs.attributeid IN (604, 605, 606, 609, 610) 
      AND ($chargesizevalue IS NULL 
           OR $chargesizevalue = $modchargesizevalue) AND invtypes.published = 1");

	while($row = $req->fetchArray(SQLITE3_NUM)) {
		list($moduleid, $chargeid) = $row;
		if(!isset($charges[$moduleid])) {
			$charges[$moduleid] = array();
		}

		$charges[$moduleid][] = $chargeid;
	}
}

function customsort(array &$charges) {
	ksort($charges);
	foreach($charges as &$typeids) {
		sort($typeids);
	}
}
