#!/usr/bin/env php
<?php
/* Author : Romain "Artefact2" Dalmaso <artefact2@gmail.com>
 * This program is free software. It comes without any warranty, to
 * the extent permitted by applicable law. You can redistribute it
 * and/or modify it under the terms of the Do What The Fuck You Want
 * To Public License, Version 2, as published by Sam Hocevar. See
 * http://sam.zoy.org/wtfpl/COPYING for more details. */

/* Create a JSON map (slottype => [typeids]) of all published modules,
 * where slottype is either "high", "medium", "low", "rig" or
 * "subsystem".
 */

require __DIR__.'/sqlite_script_common.php';

function process(SQLite3 $db, array &$modules) {
	static $moduletypes = array(
		11 => 'low',
		12 => 'high',
		13 => 'medium',
		2663 => 'rig',
		3772 => 'subsystem',
		);

	$req = $db->query('SELECT invtypes.typeid, effectid FROM invtypes JOIN dgmtypeeffects ON invtypes.typeid = dgmtypeeffects.typeid AND effectid IN ('.implode(',', array_keys($moduletypes)).') WHERE invtypes.published = 1');

	foreach($moduletypes as $type) {
		$modules[$type] = array();
	}

	while($row = $req->fetchArray(SQLITE3_NUM)) {
		$modules[$moduletypes[$row[1]]][] = $row[0];
	}
}

function customsort(array &$modules) {
	ksort($modules);
	foreach($modules as &$typeids) {
		sort($typeids);
	}
}
